target "LYLuckyCardDemo" do
	platform :ios, '10.0'

    use_frameworks!
    #消除第三方库警告

inhibit_all_warnings!

# Andrew新增

pod 'Masonry'             		 # 布局自动适应库
pod 'MJExtension'      			 # 字典转数据模型库
pod'FLAnimatedImage','~> 1.0'            # 高效 GIF加载引擎
pod 'SDWebImage', '~> 3.7.2'             # 高效 图片加载引擎
pod 'YYCategories'      		 # Category 类型工具库（YYKit 组件之一）
pod 'SGBrowserView'            		 # 弹窗或隐藏
end